### ISSUE TITLE
Indicate license terms.

### ISSUE THREAD

**Issue by AndrewJHallEsq** [KonradIT/insight-api#1]
Please indicate the licensing terms for the code included in the insight-api repo to let users know how and where this code can be used.  

Common methods used to declare open-source license terms (such as Apache-2.0, MIT, BSD-3-Clause, or EPL-2.0) include one or more of:
* adding a "LICENSE" file in the root directory including the text of the applicable license (e.g., the text of the Apache-2.0).  [[Python documentation](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#license-txt)];
* adding a "license" setup( ) argument in the setup.py file (e.g., 'License :: OSI Approved :: Apache-2.0 License',) [[Python documentation](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#license)]; and
* indicating or including a copy of the license text in the README file in the root directory [[Python README license statement](https://github.com/python/cpython#copyright-and-license-information)]. 

Thank you!

**Comment by KonradIT** [comment]
Settled on MIT.
